/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.ImageIcon;
import Model.*;
import Control.*;

/**
 *
 * @author 이상명'spc
 */
public class A_UnitListForm extends B_UnitListForm {//알촌 유닛리스트 프레임.

    private ImageIcon g1,g2,g3,l1,l2,l3,m1,m2,m3;
    
    /**
     * Creates new form A_UnitListForm
     */
    public A_UnitListForm() {
        initComponents();
    }
    
    public A_UnitListForm(Player p,B_BasicForm bf,GameThread thread){
        this();
        this.p = p;
        this.bf = bf;
        this.thread = thread;
        modify();
        setting();
    }
    
    public void modify(){
        g1 = new ImageIcon(getClass().getResource("/image/알촌짜장1.jpg"));
        g2 = new ImageIcon(getClass().getResource("/image/알촌짜장2.jpg"));
        g3 = new ImageIcon(getClass().getResource("/image/알촌짜장3.jpg"));
        l1 = new ImageIcon(getClass().getResource("/image/알촌불밥1.jpg"));
        l2 = new ImageIcon(getClass().getResource("/image/알촌불밥2.jpg"));
        l3 = new ImageIcon(getClass().getResource("/image/알촌불밥3.jpg"));
        m1 = new ImageIcon(getClass().getResource("/image/알촌카레1.jpg"));
        m2 = new ImageIcon(getClass().getResource("/image/알촌카레2.jpg"));
        m3 = new ImageIcon(getClass().getResource("/image/알촌카레3.jpg"));
        this.g1bt.setIcon(g1);
        this.g2bt.setIcon(g2);
        this.g3bt.setIcon(g3);
        this.l1bt.setIcon(l1);
        this.l2bt.setIcon(l2);
        this.l3bt.setIcon(l3);
        this.m1bt.setIcon(m1);
        this.m2bt.setIcon(m2);
        this.m3bt.setIcon(m3);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
