
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.ButtonGroup;
import Model.*;
import Control.*;

/**
 *
 * @author user
 */
public class SpeciesSelForm extends javax.swing.JFrame { //종족선택 프레임입니다.

    private ButtonGroup bg = new ButtonGroup();
    private Species_Selector sel;
    Species s;
    Player p;
    /**
     * Creates new form NewJFrame
     */
    public SpeciesSelForm() {
        this.setTitle("종족선택창");
        initComponents();
        groupping(); //버튼 중복방지용 그룹입니다.
        startbt.setEnabled(false);//종족미선택시 게임시작 못하게 막아줬습니다.
    }
    
    public SpeciesSelForm(Player p,Species_Selector sSel){ //위에 선언된 기본생성자를 일단 호출하고, 이 클래스의 player에 인자로 받아온 값을 대입해줍니다.
        this();
        this.p = p;
        sel = sSel;
    }
    
    private void groupping(){
        bg.add(atb);
        bg.add(itb);
        bg.add(jtb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atb = new javax.swing.JToggleButton();
        itb = new javax.swing.JToggleButton();
        jtb = new javax.swing.JToggleButton();
        startbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atb.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        atb.setText("Alchon");
        atb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atbActionPerformed(evt);
            }
        });

        itb.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        itb.setText("Isaac");
        itb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itbActionPerformed(evt);
            }
        });

        jtb.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        jtb.setText("JJanDon");
        jtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbActionPerformed(evt);
            }
        });

        startbt.setText("게임 시작");
        startbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("돋움", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("종족설명");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(startbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atb, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(itb, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtb, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startbt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atbActionPerformed
        jTextArea1.setText("알촌.\n가격도 평균 맛도 평균이다.");
        s = new Alchon();      
        startbt.setEnabled(true);
    }//GEN-LAST:event_atbActionPerformed

    private void itbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itbActionPerformed
        jTextArea1.setText("이삭토스트. \n빠르고, 가격이 싸다. \n허나 맛과 포만감은...");
        s = new Isaac();
        startbt.setEnabled(true);
    }//GEN-LAST:event_itbActionPerformed

    private void jtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbActionPerformed
        jTextArea1.setText("짱돈. \n가격이 좀 세지만 \n양이많고 맛이 좋은 편.");
        s = new JJangDon();
        startbt.setEnabled(true);
    }//GEN-LAST:event_jtbActionPerformed

    //클릭해줄때마다 해당종족을 임시로 저장해줍니다.
    
    private void startbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtActionPerformed
        //스타트 누르면 아까 받은 플레이어 즉, 메인의 플레이어의 종족에 임시로 저장해뒀던 종족을 넘겨줍니다.
        //그리고 인자로 받아온 selector의 generateBF를 다시 플레이어를 토스해주면서 호출하고 창을 종료합니다.
        p.setPlayerSp(s);
        sel.thread.SendCommand("0"+s.getName());
        WaitFrame wait = new WaitFrame();
        wait.setVisible(true);
        while(p.e == null)
        {
            System.out.println("");
        }
        wait.dispose();
        sel.generateBF(p);
        this.dispose();
    }//GEN-LAST:event_startbtActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton atb;
    private javax.swing.JToggleButton itb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jtb;
    private javax.swing.JButton startbt;
    // End of variables declaration//GEN-END:variables
}
