/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import KUspital.*;
import javax.swing.*;
/**
 *
 * @author user
 */
public class PatientHome extends Home {
    DefaultListModel dlm;
    MainSystem ms;
    /**
     * Creates new form NewJFrame2
     */
    public PatientHome(MainSystem ms) {
        super();
        dlm=new DefaultListModel();
        this.ms=ms;
        setTitle("환자접속");
        initComponents();
        this.jList1.setModel(dlm);
        super.jPanel2.remove(jLabel7);
        super.jButton7.setText("도움말");
        super.jButton2.setText("내 정보");
        super.jButton3.setText("의사 정보");
        super.jButton8.setText("로그 아웃");
        super.jButton4.setText("종료");
        super.jButton5.setText("방 들어가기");
        super.jButton1.setText("상담 신청");
        buttonModi();
        listInitialiser();
        this.jLabel5.setText(jLabel5.getText()+ ms.my_uno);
        this.jLabel2.setText(jLabel2.getText()+ ms.my_name);
        this.jLabel3.setText(jLabel3.getText()+ String.valueOf(ms.my_age));
        this.jLabel4.setText(jLabel4.getText()+ ms.my_gender);
        this.jLabel6.setText(jLabel6.getText()+ ms.my_phone);

        setVisible(true);
    }
    public void listInitialiser()
    {
        int[] list= ms.DBoutput.getMyDocList(ms.my_uno);
        for(int i=0;i<5;i++)
        {
            if(list[i] != 0)
            {
                dlm.addElement(ms.DBoutput.get_information(list[i], "ID"));
            }
        }
    }

        public void buttonModi(){
        this.jButton3.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
        MyDocList e=new MyDocList(ms);
        dispose();
            }
        });
        
        this.jButton4.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                   dispose();
            }
        });
        this.jButton1.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                     PatientChooseDoctor cd=new PatientChooseDoctor(ms);
            }
        });
        this.jButton5.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                   Waiting w=new Waiting();
                    ms.startChat(String.valueOf(jList1.getSelectedValue()), w);

            }
        });
        this.jButton8.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                    Login l=new Login(ms);
        dispose();
            }
        });
        this.jButton2.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
            PatientInfo pi=new PatientInfo(ms);
            dispose();
            }
        });
        this.jButton9.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                    Account a=new Account(ms);
        dispose();
            }
        });
        this.jButton7.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
        PatientHelp phelp=new PatientHelp();
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
